name: Sonarcloud analysis
env:
  sonarcloud_project_name: 'tsabri_msdocs-app-service-sqldb-dotnetcore'
  sonarcloud_organization: 'theosab2'
on:
  workflow_dispatch:
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reportings
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_GITHUB }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=${{ env.sonarcloud_organization }}
          -Dsonar.projectKey=${{ env.sonarcloud_project_name }}